### ISSUE TITLE
License ?

### ISSUE THREAD

**Issue by suprafun** [mstefarov/SuperImageEvolver#3]
Hello, under what license is this project released under ? Thank-you.

**Comment by mstefarov** [comment]
All SuperImageEvolver source code is now under [Creative Commons Zero v1.0 Universal](https://creativecommons.org/publicdomain/zero/1.0/) (CC0) -- it is free from copyright, and you can use it in any way you choose.

**Comment by suprafun** [comment]
Thank you so very much for the generous licensing :) One small thing I just noticed, you mention that your work is based on two other projects, I just checked and they seem to be under different licenses (one used MIT and the other uses LGPL). Does this affect your project ? I am more worried about the LGPL project. In my case, I would like to study your project closely so I can learn more about meta-heuristics and how they are used, so I can implement my own code. Your project seems to have some very cool ideas, and is generously licensed (thank-you) but I don't know if any LGPL code was used, which would hamper me from closely studying it (e.g. learning some code tricks). So I just want to make sure. Thank-you.

**Comment by mstefarov** [comment]
Perhaps I should've said that SuperImageEvolver was _inspired_ by those projects, not _based_ on them.  That's where I got the general "use a DNA made of random polygons to approximate an image" idea.  All of SIE's source code was written independently, without looking at the implementation of either AlteredQualia or Roger Alsing.  So dig in, if you dare!  The code I've written 8-9 years ago looks very messy to my current self :)

**Comment by suprafun** [comment]
Thank-you so very much. I am sure it will be a wonderful resource to learn from. Thank you again.
